export const FETCH_COMICS_REQUEST = 'FETCH_COMICS_REQUEST';
export const FETCH_COMICS_FAILURE = 'FETCH_COMICS_FAILURE';
export const FETCH_COMICS_SUCCESS = 'FETCH_COMICS_SUCCESS';

export const FETCH_PUBLISHERS_REQUEST = 'FETCH_PUBLISHERS_REQUEST';
export const FETCH_PUBLISHERS_FAILURE = 'FETCH_PUBLISHERS_FAILURE';
export const FETCH_PUBLISHERS_SUCCESS = 'FETCH_PUBLISHERS_SUCCESS';
