export const FETCH_COMICS_FAILURE = 'FETCH_COMICS_FAILURE';
export const FETCH_COMICS_SUCCESS = 'FETCH_COMICS_SUCCESS';

export const FETCH_PUBLISHERS_FAILURE = 'FETCH_PUBLISHERS_FAILURE';
export const FETCH_PUBLISHERS_SUCCESS = 'FETCH_PUBLISHERS_SUCCESS';

export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';

export const ADD_READ_FAILURE = 'ADD_READ_FAILURE';
export const ADD_READ_SUCCESS = 'ADD_READ_SUCCESS';

export const ADD_WISH_FAILURE = 'ADD_WISH_FAILURE';
export const ADD_WISH_SUCCESS = 'ADD_WISH_SUCCESS';

export const REMOVE_READ_FAILURE = 'REMOVE_READ_FAILURE';
export const REMOVE_READ_SUCCESS = 'REMOVE_READ_SUCCESS';

export const REMOVE_WISH_FAILURE = 'REMOVE_WISH_FAILURE';
export const REMOVE_WISH_SUCCESS = 'REMOVE_WISH_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
